name: 'Generate Doc'
description: 'Builds the Antora documentation for lib/gil/doc'
runs:
  using: composite
  steps:
    - run: |
        cd ../boost-root/libs/gil/doc
        bash build_antora.sh
        cd ..
        chmod +x $GITHUB_WORKSPACE/.github/actions/generate-doc/docs-config.sh
        $GITHUB_WORKSPACE/.github/actions/generate-doc/docs-config.sh
      shell: bash
