##############################################################################
# CircleCI 2.0 for Boost.GIL
#
# Copyright (c) 2018 Mateusz Loskot <mateusz@loskot.net>
#
# Use, modification and distribution is subject to the Boost Software License,
# Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
##############################################################################
version: 2

##############################################################################
# Docker images
##############################################################################
docker_gcc48: &docker_gcc48
  docker:
    - image: gcc:4.8
docker_gcc49: &docker_gcc49
  docker:
    - image: gcc:4.9

docker_gcc51: &docker_gcc51
  docker:
    - image: gcc:5.1
docker_gcc52: &docker_gcc52
  docker:
    - image: gcc:5.2
docker_gcc53: &docker_gcc53
  docker:
    - image: gcc:5.3
docker_gcc54: &docker_gcc54
  docker:
    - image: gcc:5.4
docker_gcc55: &docker_gcc55
  docker:
    - image: gcc:5.5

docker_gcc61: &docker_gcc61
  docker:
    - image: gcc:6.1
docker_gcc62: &docker_gcc62
  docker:
    - image: gcc:6.2
docker_gcc63: &docker_gcc63
  docker:
    - image: gcc:6.3
docker_gcc64: &docker_gcc64
  docker:
    - image: gcc:6.4

docker_gcc71: &docker_gcc71
  docker:
    - image: gcc:7.3
docker_gcc72: &docker_gcc72
  docker:
    - image: gcc:7.2
docker_gcc73: &docker_gcc73
  docker:
    - image: gcc:7.3

docker_gcc81: &docker_gcc81
  docker:
    - image: gcc:8.1

docker_clang39: &docker_clang39
  docker:
    - image: rferraro/cxx-clang:3.9

docker_clang40: &docker_clang40
  docker:
    - image: rferraro/cxx-clang:4.0

docker_clang50: &docker_clang50
  docker:
    - image: rferraro/cxx-clang:5.0

##############################################################################
# Build variants
##############################################################################
env_gcc_cpp11_dbg: &env_gcc_cpp11_dbg
  environment:
    - TOOLSET: gcc
    - VARIANT: "variant=debug"
    - OPTIMIZ: ""
    - CXXFLAG: "-std=c++11"
    - LNKFLAG: ""

env_gcc_cpp11_opt_speed: &env_gcc_cpp11_opt_speed
  environment:
    - TOOLSET: gcc
    - VARIANT: "variant=release"
    - OPTIMIZ: "optimization=speed"
    - CXXFLAG: "-std=c++11"
    - LNKFLAG: ""

env_clang_cpp11_dbg: &env_clang_cpp11_dbg
  environment:
    - TOOLSET: clang
    - VARIANT: "variant=debug"
    - OPTIMIZ: ""
    - CXXFLAG: "-std=c++11"
    - LNKFLAG: ""

env_clang_cpp11_opt_speed: &env_clang_cpp11_opt_speed
  environment:
    - TOOLSET: clang
    - VARIANT: "variant=release"
    - OPTIMIZ: "optimization=speed"
    - CXXFLAG: "-std=c++11"
    - LNKFLAG: ""

##############################################################################
# Build configurations
##############################################################################
config_gcc48_cpp11_dbg: &config_gcc48_cpp11_dbg
  <<: *docker_gcc48
  <<: *env_gcc_cpp11_dbg
config_gcc48_cpp11_opt_speed: &config_gcc48_cpp11_opt_speed
  <<: *docker_gcc48
  <<: *env_gcc_cpp11_opt_speed

config_gcc49_cpp11_dbg: &config_gcc49_cpp11_dbg
  <<: *docker_gcc49
  <<: *env_gcc_cpp11_dbg
config_gcc49_cpp11_opt_speed: &config_gcc49_cpp11_opt_speed
  <<: *docker_gcc49
  <<: *env_gcc_cpp11_opt_speed

config_gcc51_cpp11_dbg: &config_gcc51_cpp11_dbg
  <<: *docker_gcc51
  <<: *env_gcc_cpp11_dbg
config_gcc51_cpp11_opt_speed: &config_gcc51_cpp11_opt_speed
  <<: *docker_gcc51
  <<: *env_gcc_cpp11_opt_speed

config_gcc52_cpp11_dbg: &config_gcc52_cpp11_dbg
  <<: *docker_gcc52
  <<: *env_gcc_cpp11_dbg
config_gcc52_cpp11_opt_speed: &config_gcc52_cpp11_opt_speed
  <<: *docker_gcc52
  <<: *env_gcc_cpp11_opt_speed

config_gcc53_cpp11_dbg: &config_gcc53_cpp11_dbg
  <<: *docker_gcc53
  <<: *env_gcc_cpp11_dbg
config_gcc53_cpp11_opt_speed: &config_gcc53_cpp11_opt_speed
  <<: *docker_gcc53
  <<: *env_gcc_cpp11_opt_speed

config_gcc54_cpp11_dbg: &config_gcc54_cpp11_dbg
  <<: *docker_gcc54
  <<: *env_gcc_cpp11_dbg
config_gcc54_cpp11_opt_speed: &config_gcc54_cpp11_opt_speed
  <<: *docker_gcc54
  <<: *env_gcc_cpp11_opt_speed

config_gcc55_cpp11_dbg: &config_gcc55_cpp11_dbg
  <<: *docker_gcc55
  <<: *env_gcc_cpp11_dbg
config_gcc55_cpp11_opt_speed: &config_gcc55_cpp11_opt_speed
  <<: *docker_gcc55
  <<: *env_gcc_cpp11_opt_speed

config_gcc61_cpp11_dbg: &config_gcc61_cpp11_dbg
  <<: *docker_gcc61
  <<: *env_gcc_cpp11_dbg
config_gcc61_cpp11_opt_speed: &config_gcc61_cpp11_opt_speed
  <<: *docker_gcc61
  <<: *env_gcc_cpp11_opt_speed

config_gcc62_cpp11_dbg: &config_gcc62_cpp11_dbg
  <<: *docker_gcc62
  <<: *env_gcc_cpp11_dbg
config_gcc62_cpp11_opt_speed: &config_gcc62_cpp11_opt_speed
  <<: *docker_gcc62
  <<: *env_gcc_cpp11_opt_speed

config_gcc63_cpp11_dbg: &config_gcc63_cpp11_dbg
  <<: *docker_gcc63
  <<: *env_gcc_cpp11_dbg
config_gcc63_cpp11_opt_speed: &config_gcc63_cpp11_opt_speed
  <<: *docker_gcc63
  <<: *env_gcc_cpp11_opt_speed

config_gcc64_cpp11_dbg: &config_gcc64_cpp11_dbg
  <<: *docker_gcc64
  <<: *env_gcc_cpp11_dbg
config_gcc64_cpp11_opt_speed: &config_gcc64_cpp11_opt_speed
  <<: *docker_gcc64
  <<: *env_gcc_cpp11_opt_speed

config_gcc71_cpp11_dbg: &config_gcc71_cpp11_dbg
  <<: *docker_gcc71
  <<: *env_gcc_cpp11_dbg
config_gcc71_cpp11_opt_speed: &config_gcc71_cpp11_opt_speed
  <<: *docker_gcc71
  <<: *env_gcc_cpp11_opt_speed

config_gcc72_cpp11_dbg: &config_gcc72_cpp11_dbg
  <<: *docker_gcc72
  <<: *env_gcc_cpp11_dbg
config_gcc72_cpp11_opt_speed: &config_gcc72_cpp11_opt_speed
  <<: *docker_gcc72
  <<: *env_gcc_cpp11_opt_speed

config_gcc73_cpp11_dbg: &config_gcc73_cpp11_dbg
  <<: *docker_gcc73
  <<: *env_gcc_cpp11_dbg
config_gcc73_cpp11_opt_speed: &config_gcc73_cpp11_opt_speed
  <<: *docker_gcc73
  <<: *env_gcc_cpp11_opt_speed

config_gcc81_cpp11_dbg: &config_gcc81_cpp11_dbg
  <<: *docker_gcc81
  <<: *env_gcc_cpp11_dbg
config_gcc81_cpp11_opt_speed: &config_gcc81_cpp11_opt_speed
  <<: *docker_gcc81
  <<: *env_gcc_cpp11_opt_speed

config_clang39_cpp11_dbg: &config_clang39_cpp11_dbg
  <<: *docker_clang39
  <<: *env_clang_cpp11_dbg
config_clang39_cpp11_opt_speed: &config_clang39_cpp11_opt_speed
  <<: *docker_clang39
  <<: *env_clang_cpp11_opt_speed

config_clang40_cpp11_dbg: &config_clang40_cpp11_dbg
  <<: *docker_clang40
  <<: *env_clang_cpp11_dbg
config_clang40_cpp11_opt_speed: &config_clang40_cpp11_opt_speed
  <<: *docker_clang40
  <<: *env_clang_cpp11_opt_speed

config_clang50_cpp11_dbg: &config_clang50_cpp11_dbg
  <<: *docker_clang50
  <<: *env_clang_cpp11_dbg
config_clang50_cpp11_opt_speed: &config_clang50_cpp11_opt_speed
  <<: *docker_clang50
  <<: *env_clang_cpp11_opt_speed

##############################################################################
# Workspace persistance
##############################################################################
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

##############################################################################
# Build steps (in alphabetical order by name of steps group)
##############################################################################
run_compiler_version: &run_compiler_version
  run:
    name: Checking compiler version
    command: |
        echo TOOLSET=$TOOLSET
        echo VARIANT=$VARIANT
        echo OPTIMIZ=$OPTIMIZ
        echo CXXFLAG=$CXXFLAG
        echo LNKFLAG=$LNKFLAG
        $TOOLSET --version

steps_bootstrap: &steps_bootstrap
  steps:
    - *attach_workspace
    - *run_compiler_version
    - run: cd boost && ./bootstrap.sh -with-toolset=$TOOLSET || cat ./bootstrap.log
    - run: cd boost && ./b2 headers
    - persist_to_workspace:
        root: ~/project
        paths: boost

steps_test_core: &steps_test_core
  steps:
    - *attach_workspace
    - *run_compiler_version
    - run: cd boost && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxflags="$CXXFLAG" libs/gil/test

steps_test_toolbox: &steps_test_toolbox
  steps:
    - *attach_workspace
    - *run_compiler_version
    - run: cd boost && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxflags="$CXXFLAG" libs/gil/toolbox/test

steps_test_numeric: &steps_test_numeric
  steps:
    - *attach_workspace
    - *run_compiler_version
    - run: cd boost && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxflags="$CXXFLAG" libs/gil/numeric/test

steps_test_io: &steps_test_io
  steps:
    - *attach_workspace
    - *run_compiler_version
    - run: cd boost && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxflags="$CXXFLAG" libs/gil/io/test//simple

##############################################################################
# Build jobs
##############################################################################
jobs:
  bootstrap_checkout:
    <<: *config_gcc48_cpp11_opt_speed
    steps:
      - checkout
      - run:
          name: Checkout Boost superproject
          command: |
            git clone -b master --depth 1 https://github.com/boostorg/boost.git
            cd boost
            git submodule update --init tools/build
            git submodule update --init libs/config
            git submodule update --init tools/boostdep
            rm -rf libs/gil && mkdir -p libs/gil
            mv -t libs/gil/ ../Jamfile ../example ../include ../io ../numeric ../test ../toolbox
            python tools/boostdep/depinst/depinst.py gil
      - persist_to_workspace:
          root: ~/project
          paths: boost

  bootstrap_gcc:
    <<: *config_gcc48_cpp11_opt_speed
    <<: *steps_bootstrap

  bootstrap_clang:
    <<: *config_clang39_cpp11_opt_speed
    <<: *steps_bootstrap

  ### GCC 4.x ################################################################
  gcc48_11_core:
    <<: *config_gcc48_cpp11_dbg
    <<: *steps_test_core

  gcc48_11_core_speed:
    <<: *config_gcc48_cpp11_opt_speed
    <<: *steps_test_core

  gcc49_11_core:
    <<: *config_gcc49_cpp11_dbg
    <<: *steps_test_core

  gcc49_11_core_speed:
    <<: *config_gcc49_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 5.x ################################################################
  gcc51_11_core:
    <<: *config_gcc51_cpp11_dbg
    <<: *steps_test_core

  gcc51_11_core_speed:
    <<: *config_gcc51_cpp11_opt_speed
    <<: *steps_test_core

  gcc52_11_core:
    <<: *config_gcc52_cpp11_dbg
    <<: *steps_test_core

  gcc52_11_core_speed:
    <<: *config_gcc52_cpp11_opt_speed
    <<: *steps_test_core

  gcc53_11_core:
    <<: *config_gcc53_cpp11_dbg
    <<: *steps_test_core

  gcc53_11_core_speed:
    <<: *config_gcc53_cpp11_opt_speed
    <<: *steps_test_core

  gcc54_11_core:
    <<: *config_gcc54_cpp11_dbg
    <<: *steps_test_core

  gcc54_11_core_speed:
    <<: *config_gcc54_cpp11_opt_speed
    <<: *steps_test_core

  gcc55_11_core:
    <<: *config_gcc55_cpp11_dbg
    <<: *steps_test_core

  gcc55_11_core_speed:
    <<: *config_gcc55_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 6.x ################################################################
  gcc61_11_core:
    <<: *config_gcc61_cpp11_dbg
    <<: *steps_test_core

  gcc61_11_core_speed:
    <<: *config_gcc61_cpp11_opt_speed
    <<: *steps_test_core

  gcc62_11_core:
    <<: *config_gcc62_cpp11_dbg
    <<: *steps_test_core

  gcc62_11_core_speed:
    <<: *config_gcc62_cpp11_opt_speed
    <<: *steps_test_core

  gcc63_11_core:
    <<: *config_gcc63_cpp11_dbg
    <<: *steps_test_core

  gcc63_11_core_speed:
    <<: *config_gcc63_cpp11_opt_speed
    <<: *steps_test_core

  gcc64_11_core:
    <<: *config_gcc64_cpp11_dbg
    <<: *steps_test_core

  gcc64_11_core_speed:
    <<: *config_gcc64_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 7.x ################################################################
  gcc71_11_core:
    <<: *config_gcc71_cpp11_dbg
    <<: *steps_test_core

  gcc71_11_core_speed:
    <<: *config_gcc71_cpp11_opt_speed
    <<: *steps_test_core

  gcc72_11_core:
    <<: *config_gcc72_cpp11_dbg
    <<: *steps_test_core

  gcc72_11_core_speed:
    <<: *config_gcc72_cpp11_opt_speed
    <<: *steps_test_core

  gcc73_11_core:
    <<: *config_gcc73_cpp11_dbg
    <<: *steps_test_core

  gcc73_11_core_speed:
    <<: *config_gcc73_cpp11_opt_speed
    <<: *steps_test_core

  gcc81_11_core:
    <<: *config_gcc81_cpp11_dbg
    <<: *steps_test_core

  gcc81_11_core_speed:
    <<: *config_gcc81_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 3.9 ################################################################
  clang39_11_core:
    <<: *config_clang39_cpp11_dbg
    <<: *steps_test_core

  clang39_11_core_speed:
    <<: *config_clang39_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 4.0 ################################################################
  clang40_11_core:
    <<: *config_clang40_cpp11_dbg
    <<: *steps_test_core

  clang40_11_core_speed:
    <<: *config_clang40_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 5.0 ################################################################
  clang50_11_core:
    <<: *config_clang50_cpp11_dbg
    <<: *steps_test_core

  clang50_11_core_speed:
    <<: *config_clang50_cpp11_opt_speed
    <<: *steps_test_core

##############################################################################
# Workflows
##############################################################################
workflows:
  version: 2
  build-and-test:
    jobs:
      - bootstrap_checkout:
          filters:
            branches:
              only:
                - develop
                - master
      - bootstrap_gcc:
          requires:
            - bootstrap_checkout
      - bootstrap_clang:
          requires:
            - bootstrap_checkout

      ### GCC 4.x ############################################################
      - gcc48_11_core:
          requires:
            - bootstrap_gcc
      - gcc48_11_core_speed:
          requires:
            - gcc48_11_core

      - gcc49_11_core:
          requires:
            - bootstrap_gcc
      - gcc49_11_core_speed:
          requires:
            - gcc49_11_core

      ### GCC 5.x ############################################################
      - gcc51_11_core:
          requires:
            - bootstrap_gcc
      - gcc51_11_core_speed:
          requires:
            - gcc51_11_core

      - gcc52_11_core:
          requires:
            - bootstrap_gcc
      - gcc52_11_core_speed:
          requires:
            - gcc52_11_core

      - gcc53_11_core:
          requires:
            - bootstrap_gcc
      - gcc53_11_core_speed:
          requires:
            - gcc53_11_core

      - gcc54_11_core:
          requires:
            - bootstrap_gcc
      - gcc54_11_core_speed:
          requires:
            - gcc54_11_core

      - gcc55_11_core:
          requires:
            - bootstrap_gcc
      - gcc55_11_core_speed:
          requires:
            - gcc55_11_core

      ### GCC 6.x ############################################################
      - gcc61_11_core:
          requires:
            - bootstrap_gcc
      - gcc61_11_core_speed:
          requires:
            - gcc61_11_core

      - gcc62_11_core:
          requires:
            - bootstrap_gcc
      - gcc62_11_core_speed:
          requires:
            - gcc62_11_core

      - gcc63_11_core:
          requires:
            - bootstrap_gcc
      - gcc63_11_core_speed:
          requires:
            - gcc63_11_core

      - gcc64_11_core:
          requires:
            - bootstrap_gcc
      - gcc64_11_core_speed:
          requires:
            - gcc64_11_core

      ### GCC 7.x ############################################################
      - gcc71_11_core:
          requires:
            - bootstrap_gcc
      - gcc71_11_core_speed:
          requires:
            - gcc71_11_core

      - gcc72_11_core:
          requires:
            - bootstrap_gcc
      - gcc72_11_core_speed:
          requires:
            - gcc72_11_core

      - gcc73_11_core:
          requires:
            - bootstrap_gcc
      - gcc73_11_core_speed:
          requires:
            - gcc73_11_core

      - gcc81_11_core:
          requires:
            - bootstrap_gcc
      - gcc81_11_core_speed:
          requires:
            - gcc81_11_core

      ### clang 3.9 ##########################################################
      - clang39_11_core:
          requires:
            - bootstrap_clang
      - clang39_11_core_speed:
          requires:
            - clang39_11_core

      ### clang 4.0 ##########################################################
      - clang40_11_core:
          requires:
            - bootstrap_clang
      - clang40_11_core_speed:
          requires:
            - clang40_11_core

      ### clang 5.0 ##########################################################
      - clang50_11_core:
          requires:
            - bootstrap_clang
      - clang50_11_core_speed:
          requires:
            - clang50_11_core

##############################################################################
# Notifications
##############################################################################
# TODO: Waiting for notifications for workflow
# notify:
#   webhooks:
#     - url: https://webhooks.gitter.im/e/9538066016dc0f9b6511
