##############################################################################
# CircleCI 2.0 for Boost.GIL
#
# Copyright (c) 2018-2019 Mateusz Loskot <mateusz@loskot.net>
#
# Use, modification and distribution is subject to the Boost Software License,
# Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
##############################################################################
version: 2.0

##############################################################################
# Docker images
##############################################################################
docker_gcc48: &docker_gcc48
  docker:
    - image: teeks99/boost-cpp-docker:gcc-4.8

docker_gcc49: &docker_gcc49
  docker:
    - image: teeks99/boost-cpp-docker:gcc-4.9

docker_gcc5: &docker_gcc5
  docker:
    - image: teeks99/boost-cpp-docker:gcc-5

docker_gcc6: &docker_gcc6
  docker:
    - image: teeks99/boost-cpp-docker:gcc-6

docker_gcc7: &docker_gcc7
  docker:
    - image: teeks99/boost-cpp-docker:gcc-7

docker_gcc8: &docker_gcc8
  docker:
    - image: teeks99/boost-cpp-docker:gcc-8

docker_clang39: &docker_clang39
  docker:
    - image: teeks99/boost-cpp-docker:clang-3.9

docker_clang4: &docker_clang4
  docker:
    - image: teeks99/boost-cpp-docker:clang-4

docker_clang5: &docker_clang5
  docker:
    - image: teeks99/boost-cpp-docker:clang-5

docker_clang6: &docker_clang6
  docker:
    - image: teeks99/boost-cpp-docker:clang-6

docker_clang7: &docker_clang7
  docker:
    - image: teeks99/boost-cpp-docker:clang-7

docker_clang8: &docker_clang8
  docker:
    - image: teeks99/boost-cpp-docker:clang-8

docker_clang9: &docker_clang9
  docker:
    - image: teeks99/boost-cpp-docker:clang-9

##############################################################################
# Build variants
##############################################################################
env_dbg: &env_dbg
  VARIANT: "variant=debug"
  OPTIMIZ: ""

env_opt: &env_opt
  VARIANT: "variant=release"
  OPTIMIZ: "optimization=speed"

env_gcc_cpp11: &env_gcc_cpp11
  TOOLSET: gcc
  CXXSTD: "11"
  LNKFLAG: ""

env_clang_cpp11: &env_clang_cpp11
  TOOLSET: clang
  CXXSTD: "11"
  LNKFLAG: ""

##############################################################################
# Build configurations
##############################################################################
# GCC 4.8 is used to build `b2` driver
config_gcc48_cpp11_opt_speed: &config_gcc48_cpp11_opt_speed
  <<: *docker_gcc48
  environment:
    TOOLSET_VERSION: 4.8
    <<: [*env_gcc_cpp11, *env_opt]

config_gcc49_cpp11_dbg: &config_gcc49_cpp11_dbg
  <<: *docker_gcc49
  environment:
    TOOLSET_VERSION: 4.9
    <<: [*env_gcc_cpp11, *env_dbg]
config_gcc49_cpp11_opt_speed: &config_gcc49_cpp11_opt_speed
  <<: *docker_gcc49
  environment:
    TOOLSET_VERSION: 4.9
    <<: [*env_gcc_cpp11, *env_opt]

config_gcc5_cpp11_dbg: &config_gcc5_cpp11_dbg
  <<: *docker_gcc5
  environment:
    TOOLSET_VERSION: 5
    <<: [*env_gcc_cpp11, *env_dbg]
config_gcc5_cpp11_opt_speed: &config_gcc5_cpp11_opt_speed
  <<: *docker_gcc5
  environment:
    TOOLSET_VERSION: 5
    <<: [*env_gcc_cpp11, *env_opt]

config_gcc6_cpp11_dbg: &config_gcc6_cpp11_dbg
  <<: *docker_gcc6
  environment:
    TOOLSET_VERSION: 6
    <<: [*env_gcc_cpp11, *env_dbg]
config_gcc6_cpp11_opt_speed: &config_gcc6_cpp11_opt_speed
  <<: *docker_gcc6
  environment:
    TOOLSET_VERSION: 6
    <<: [*env_gcc_cpp11, *env_opt]

config_gcc7_cpp11_dbg: &config_gcc7_cpp11_dbg
  <<: *docker_gcc7
  environment:
    TOOLSET_VERSION: 7
    <<: [*env_gcc_cpp11, *env_dbg]
config_gcc7_cpp11_opt_speed: &config_gcc7_cpp11_opt_speed
  <<: *docker_gcc7
  environment:
    TOOLSET_VERSION: 7
    <<: [*env_gcc_cpp11, *env_opt]

config_gcc8_cpp11_dbg: &config_gcc8_cpp11_dbg
  <<: *docker_gcc8
  environment:
    TOOLSET_VERSION: 8
    <<: [*env_gcc_cpp11, *env_dbg]
config_gcc8_cpp11_opt_speed: &config_gcc8_cpp11_opt_speed
  <<: *docker_gcc8
  environment:
    TOOLSET_VERSION: 8
    <<: [*env_gcc_cpp11, *env_opt]

config_clang39_cpp11_dbg: &config_clang39_cpp11_dbg
  <<: *docker_clang39
  environment:
    TOOLSET_VERSION: 3.9
    <<: [*env_clang_cpp11, *env_dbg]
config_clang39_cpp11_opt_speed: &config_clang39_cpp11_opt_speed
  <<: *docker_clang39
  environment:
    TOOLSET_VERSION: 3.9
    <<: [*env_clang_cpp11, *env_opt]

config_clang4_cpp11_dbg: &config_clang4_cpp11_dbg
  <<: *docker_clang4
  environment:
    TOOLSET_VERSION: 4.0
    <<: [*env_clang_cpp11, *env_dbg]
config_clang4_cpp11_opt_speed: &config_clang4_cpp11_opt_speed
  <<: *docker_clang4
  environment:
    TOOLSET_VERSION: 4.0
    <<: [*env_clang_cpp11, *env_opt]

config_clang5_cpp11_dbg: &config_clang5_cpp11_dbg
  <<: *docker_clang5
  environment:
    TOOLSET_VERSION: 5.0
    <<: [*env_clang_cpp11, *env_dbg]
config_clang5_cpp11_opt_speed: &config_clang5_cpp11_opt_speed
  <<: *docker_clang5
  environment:
    TOOLSET_VERSION: 5.0
    <<: [*env_clang_cpp11, *env_opt]

config_clang6_cpp11_dbg: &config_clang6_cpp11_dbg
  <<: *docker_clang6
  environment:
    TOOLSET_VERSION: 6.0
    <<: [*env_clang_cpp11, *env_dbg]
config_clang6_cpp11_opt_speed: &config_clang6_cpp11_opt_speed
  <<: *docker_clang6
  environment:
    TOOLSET_VERSION: 6.0
    <<: [*env_clang_cpp11, *env_opt]

config_clang7_cpp11_dbg: &config_clang7_cpp11_dbg
  <<: *docker_clang7
  environment:
    TOOLSET_VERSION: 7
    <<: [*env_clang_cpp11, *env_dbg]
config_clang7_cpp11_opt_speed: &config_clang7_cpp11_opt_speed
  <<: *docker_clang7
  environment:
    TOOLSET_VERSION: 7
    <<: [*env_clang_cpp11, *env_opt]

config_clang8_cpp11_dbg: &config_clang8_cpp11_dbg
  <<: *docker_clang8
  environment:
    TOOLSET_VERSION: 8
    <<: [*env_clang_cpp11, *env_dbg]
config_clang8_cpp11_opt_speed: &config_clang8_cpp11_opt_speed
  <<: *docker_clang8
  environment:
    TOOLSET_VERSION: 8
    <<: [*env_clang_cpp11, *env_opt]

config_clang9_cpp11_dbg: &config_clang9_cpp11_dbg
  <<: *docker_clang9
  environment:
    TOOLSET_VERSION: 9
    <<: [*env_clang_cpp11, *env_dbg]
config_clang9_cpp11_opt_speed: &config_clang9_cpp11_opt_speed
  <<: *docker_clang9
  environment:
    TOOLSET_VERSION: 9
    <<: [*env_clang_cpp11, *env_opt]

##############################################################################
# Workspace persistance
##############################################################################
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

##############################################################################
# Build steps (in alphabetical order by name of steps group)
##############################################################################
run_compiler_version: &run_compiler_version
  run:
    name: Checking compiler version
    command: |
        echo TOOLSET=$TOOLSET
        echo TOOLSET_VERSION=$TOOLSET_VERSION
        echo VARIANT=$VARIANT
        echo OPTIMIZ=$OPTIMIZ
        echo CXXSTD=$CXXSTD
        echo LNKFLAG=$LNKFLAG
        "${TOOLSET}-${TOOLSET_VERSION}" --version

run_project_config: &run_project_config
  run:
    name: Configure project-config.jam
    command: |
        echo "using $TOOLSET : : ${TOOLSET}-${TOOLSET_VERSION} ;" > boost-root/project-config.jam

steps_bootstrap: &steps_bootstrap
  steps:
    - *attach_workspace
    - *run_compiler_version
    - *run_project_config
    - run: cd boost-root && ./bootstrap.sh -with-toolset=$TOOLSET || cat ./bootstrap.log
    - run: cd boost-root && ./b2 headers > /dev/null
    - persist_to_workspace:
        root: ~/project
        paths: boost-root

steps_test_core: &steps_test_core
  steps:
    - *attach_workspace
    - *run_compiler_version
    - *run_project_config
    - run: cd boost-root && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxstd="$CXXSTD" libs/gil/test

steps_test_toolbox: &steps_test_toolbox
  steps:
    - *attach_workspace
    - *run_compiler_version
    - *run_project_config
    - run: cd boost-root && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxstd="$CXXSTD" libs/gil/toolbox/test

steps_test_numeric: &steps_test_numeric
  steps:
    - *attach_workspace
    - *run_compiler_version
    - *run_project_config
    - run: cd boost-root && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxstd="$CXXSTD" libs/gil/numeric/test

steps_test_io: &steps_test_io
  steps:
    - *attach_workspace
    - *run_compiler_version
    - *run_project_config
    - run: cd boost-root && ./b2 toolset=$TOOLSET $VARIANT $OPTIMIZ cxxstd="$CXXSTD" libs/gil/io/test//simple

##############################################################################
# Build jobs
##############################################################################
jobs:
  bootstrap_checkout:
    working_directory: ~/project/gil
    # Build `b2` using the ancient compiler to hopefully avoid run-time failures:
    # ./b2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./b2)
    <<: *config_gcc48_cpp11_opt_speed
    steps:
      - checkout
      - run:
          # CONTRIBUTING.md: Modular Boost Library Maintenance guide, for more realistic
          # test environment, recommends to develop and test individual Boost library
          # against other Boost libraries as defined by the Boost super-project master branch
          name: Checkout Boost superproject
          command: |
            echo $PWD && ls -a $PWD
            cd ..
            echo $PWD && ls -a $PWD
            ~/project/gil/.ci/get-boost.sh $CIRCLE_BRANCH ~/project/gil
            cd boost-root
      - persist_to_workspace:
          root: ~/project
          paths: boost-root

  bootstrap_gcc:
    <<: *config_gcc48_cpp11_opt_speed
    <<: *steps_bootstrap

  bootstrap_clang:
    <<: *config_clang39_cpp11_opt_speed
    <<: *steps_bootstrap

  ### GCC 4.x ################################################################
  gcc49_11_core:
    <<: *config_gcc49_cpp11_dbg
    <<: *steps_test_core

  gcc49_11_core_speed:
    <<: *config_gcc49_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 5.x ################################################################
  gcc5_11_core:
    <<: *config_gcc5_cpp11_dbg
    <<: *steps_test_core

  gcc5_11_core_speed:
    <<: *config_gcc5_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 6.x ################################################################
  gcc6_11_core:
    <<: *config_gcc6_cpp11_dbg
    <<: *steps_test_core

  gcc6_11_core_speed:
    <<: *config_gcc6_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 7.x ################################################################
  gcc7_11_core:
    <<: *config_gcc7_cpp11_dbg
    <<: *steps_test_core

  gcc7_11_core_speed:
    <<: *config_gcc7_cpp11_opt_speed
    <<: *steps_test_core

  ### GCC 8.x ################################################################
  gcc8_11_core:
    <<: *config_gcc8_cpp11_dbg
    <<: *steps_test_core

  gcc8_11_core_speed:
    <<: *config_gcc8_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 3.9 ################################################################
  clang39_11_core:
    <<: *config_clang39_cpp11_dbg
    <<: *steps_test_core

  clang39_11_core_speed:
    <<: *config_clang39_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 4.x ################################################################
  clang4_11_core:
    <<: *config_clang4_cpp11_dbg
    <<: *steps_test_core

  clang4_11_core_speed:
    <<: *config_clang4_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 5.x ################################################################
  clang5_11_core:
    <<: *config_clang5_cpp11_dbg
    <<: *steps_test_core

  clang5_11_core_speed:
    <<: *config_clang5_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 6.x ################################################################
  clang6_11_core:
    <<: *config_clang6_cpp11_dbg
    <<: *steps_test_core

  clang6_11_core_speed:
    <<: *config_clang6_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 7.x ################################################################
  clang7_11_core:
    <<: *config_clang7_cpp11_dbg
    <<: *steps_test_core

  clang7_11_core_speed:
    <<: *config_clang7_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 8.x ################################################################
  clang8_11_core:
    <<: *config_clang8_cpp11_dbg
    <<: *steps_test_core

  clang8_11_core_speed:
    <<: *config_clang8_cpp11_opt_speed
    <<: *steps_test_core

  ### clang 9.x ################################################################
  clang9_11_core:
    <<: *config_clang9_cpp11_dbg
    <<: *steps_test_core

  clang9_11_core_speed:
    <<: *config_clang9_cpp11_opt_speed
    <<: *steps_test_core

##############################################################################
# Workflows
##############################################################################
workflows:
  version: 2
  build-and-test:
    jobs:
      - bootstrap_checkout
      - bootstrap_gcc:
          requires:
            - bootstrap_checkout
      - bootstrap_clang:
          requires:
            - bootstrap_checkout

      ### GCC 4.x ############################################################
      - gcc49_11_core:
          requires:
            - bootstrap_gcc
      - gcc49_11_core_speed:
          requires:
            - gcc49_11_core

      ### GCC 5.x ############################################################
      - gcc5_11_core:
          requires:
            - bootstrap_gcc
      - gcc5_11_core_speed:
          requires:
            - gcc5_11_core

      ### GCC 6.x ############################################################
      - gcc6_11_core:
          requires:
            - bootstrap_gcc
      - gcc6_11_core_speed:
          requires:
            - gcc6_11_core

      ### GCC 7.x ############################################################
      - gcc7_11_core:
          requires:
            - bootstrap_gcc
      - gcc7_11_core_speed:
          requires:
            - gcc7_11_core

      ### GCC 8.x ############################################################
      - gcc8_11_core:
          requires:
            - bootstrap_gcc
      - gcc8_11_core_speed:
          requires:
            - gcc8_11_core

      ### clang 3.9 ##########################################################
      - clang39_11_core:
          requires:
            - bootstrap_clang
      - clang39_11_core_speed:
          requires:
            - clang39_11_core

      ### clang 4.x ##########################################################
      - clang4_11_core:
          requires:
            - bootstrap_clang
      - clang4_11_core_speed:
          requires:
            - clang4_11_core

      ### clang 5.x ##########################################################
      - clang5_11_core:
          requires:
            - bootstrap_clang
      - clang5_11_core_speed:
          requires:
            - clang5_11_core
      ### clang 6.x ##########################################################
      - clang6_11_core:
          requires:
            - bootstrap_clang
      - clang6_11_core_speed:
          requires:
            - clang6_11_core

      ### clang 7.x ##########################################################
      - clang7_11_core:
          requires:
            - bootstrap_clang
      - clang7_11_core_speed:
          requires:
            - clang7_11_core

      ### clang 8.x ##########################################################
      - clang8_11_core:
          requires:
            - bootstrap_clang
      - clang8_11_core_speed:
          requires:
            - clang8_11_core

      ### clang 9.x ##########################################################
      - clang9_11_core:
          requires:
            - bootstrap_clang
      - clang9_11_core_speed:
          requires:
            - clang9_11_core

##############################################################################
# Notifications
##############################################################################
# Circle CI 1.0 notifications seem to work for Circle CI 2.0 (not 2.1!)
# https://github.com/circleci/circleci-docs/issues/2411
# https://discuss.circleci.com/t/circleci-2-0-notifications-webhooks/19075/9
#
# TODO: Disabled until CircleCI supports single notification per whole workflow.
#       Currently, it floods the webhook with a notification per job.
#notify:
#  webhooks:
#    - url: https://webhooks.gitter.im/e/9538066016dc0f9b6511
