# Azure Pipelines for Boost.GIL
#
# Copyright 2018-2019 Mateusz Loskot <mateusz at loskot dot net>
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
steps:
  - script: cmake --version
    displayName: 'Check CMake'
