# CMake generated Testfile for 
# Source directory: /home/prathamesh/gil/test/extension/toolbox
# Build directory: /home/prathamesh/gil/test/extension/toolbox
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(t_ext_toolbox_channel_type "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_channel_type")
set_tests_properties(t_ext_toolbox_channel_type PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_channel_view "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_channel_view")
set_tests_properties(t_ext_toolbox_channel_view PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_cmyka "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_cmyka")
set_tests_properties(t_ext_toolbox_color_convert_cmyka PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_gray "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_gray")
set_tests_properties(t_ext_toolbox_color_convert_gray PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_gray_alpha "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_gray_alpha")
set_tests_properties(t_ext_toolbox_color_convert_gray_alpha PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_hsl "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_hsl")
set_tests_properties(t_ext_toolbox_color_convert_hsl PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_hsv "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_hsv")
set_tests_properties(t_ext_toolbox_color_convert_hsv PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_lab "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_lab")
set_tests_properties(t_ext_toolbox_color_convert_lab PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_luminance "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_luminance")
set_tests_properties(t_ext_toolbox_color_convert_luminance PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_color_convert_xyz "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_color_convert_xyz")
set_tests_properties(t_ext_toolbox_color_convert_xyz PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_get_num_bits "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_get_num_bits")
set_tests_properties(t_ext_toolbox_get_num_bits PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_get_pixel_type "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_get_pixel_type")
set_tests_properties(t_ext_toolbox_get_pixel_type PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_is_bit_aligned "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_is_bit_aligned")
set_tests_properties(t_ext_toolbox_is_bit_aligned PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_is_homogeneous "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_is_homogeneous")
set_tests_properties(t_ext_toolbox_is_homogeneous PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_pixel_bit_size "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_pixel_bit_size")
set_tests_properties(t_ext_toolbox_pixel_bit_size PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_subchroma_image "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_subchroma_image")
set_tests_properties(t_ext_toolbox_subchroma_image PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;39;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
add_test(t_ext_toolbox_indexed_image "/home/prathamesh/gil/test/extension/toolbox/test_ext_toolbox_indexed_image")
set_tests_properties(t_ext_toolbox_indexed_image PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;59;add_test;/home/prathamesh/gil/test/extension/toolbox/CMakeLists.txt;0;")
