# CMake generated Testfile for 
# Source directory: /home/prathamesh/gil/test/core/image_view
# Build directory: /home/prathamesh/gil/test/core/image_view
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(t_core_image_view_axis_iterator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_axis_iterator")
set_tests_properties(t_core_image_view_axis_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_collection "/home/prathamesh/gil/test/core/image_view/test_core_image_view_collection")
set_tests_properties(t_core_image_view_collection PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_concepts "/home/prathamesh/gil/test/core/image_view/test_core_image_view_concepts")
set_tests_properties(t_core_image_view_concepts PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_derived_view_type "/home/prathamesh/gil/test/core/image_view/test_core_image_view_derived_view_type")
set_tests_properties(t_core_image_view_derived_view_type PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_dynamic_step "/home/prathamesh/gil/test/core/image_view/test_core_image_view_dynamic_step")
set_tests_properties(t_core_image_view_dynamic_step PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_is_planar "/home/prathamesh/gil/test/core/image_view/test_core_image_view_is_planar")
set_tests_properties(t_core_image_view_is_planar PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_iterator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_iterator")
set_tests_properties(t_core_image_view_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_planar_rgba_view "/home/prathamesh/gil/test/core/image_view/test_core_image_view_planar_rgba_view")
set_tests_properties(t_core_image_view_planar_rgba_view PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_reverse_iterator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_reverse_iterator")
set_tests_properties(t_core_image_view_reverse_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_subimage_view "/home/prathamesh/gil/test/core/image_view/test_core_image_view_subimage_view")
set_tests_properties(t_core_image_view_subimage_view PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_view_is_basic "/home/prathamesh/gil/test/core/image_view/test_core_image_view_view_is_basic")
set_tests_properties(t_core_image_view_view_is_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_view_is_mutable "/home/prathamesh/gil/test/core/image_view/test_core_image_view_view_is_mutable")
set_tests_properties(t_core_image_view_view_is_mutable PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_view_is_step "/home/prathamesh/gil/test/core/image_view/test_core_image_view_view_is_step")
set_tests_properties(t_core_image_view_view_is_step PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_view_type "/home/prathamesh/gil/test/core/image_view/test_core_image_view_view_type")
set_tests_properties(t_core_image_view_view_type PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_x_iterator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_x_iterator")
set_tests_properties(t_core_image_view_x_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_xy_locator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_xy_locator")
set_tests_properties(t_core_image_view_xy_locator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_y_iterator "/home/prathamesh/gil/test/core/image_view/test_core_image_view_y_iterator")
set_tests_properties(t_core_image_view_y_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
add_test(t_core_image_view_view_type_from_pixel "/home/prathamesh/gil/test/core/image_view/test_core_image_view_view_type_from_pixel")
set_tests_properties(t_core_image_view_view_type_from_pixel PROPERTIES  _BACKTRACE_TRIPLES "/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;38;add_test;/home/prathamesh/gil/test/core/image_view/CMakeLists.txt;0;")
