name: 'Generate Doc'
description: 'Runs b2 on lib/gil/doc to generate documentation'
inputs:
  github_token:
    description: 'Github Token for Access'
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "using doxygen ;" > ~/user-config.jam
        cd ../boost-root/libs
        ../b2 gil/doc
        cd gil
        chmod +x $GITHUB_WORKSPACE/.github/actions/generate-publish-doc/upload-script.sh
        $GITHUB_WORKSPACE/.github/actions/generate-publish-doc/upload-script.sh ${{inputs.github_token}}
      shell: bash
