name: 'Get Docs Prerequisites'
description: 'Downloads all the necessary packages for building documentation'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
