name: Docs-Build
on:
  push:
    branches:
      - master
      - develop

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docs-prerequisites
      - uses: ./.github/actions/setup-boost
      - uses: ./.github/actions/generate-doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: temp-doc
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
